export const POSTS = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/posts/postImage1.jpg",
    user: {
      username: "ranier",
      profileImg: "/avatars/userImage1.jpg",
      fullName: "Ranier Tan",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "dea",
          profileImg: "/avatars/userImage5.jpg",
          fullName: "Dea G",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "ranier",
      profileImg: "/avatars/userImage1.jpg",
      fullName: "Ranier Tan",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "dea",
          profileImg: "/avatars/userImage5.jpg",
          fullName: "Dea G",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/postImage1.jpg",
    user: {
      username: "ranier",
      profileImg: "/avatars/userImage1.jpg",
      fullName: "Ranier Tan",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/postImage1.jpg",
    user: {
      username: "ranier",
      profileImg: "/avatars/userImage1.jpg",
      fullName: "Ranier Tan",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "dea",
          profileImg: "/avatars/userImage5.jpg",
          fullName: "Dea G",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Ranier Tan",
    username: "ranier",
    profileImg: "/avatars/userImage1.jpg",
  },
  {
    _id: "2",
    fullName: "Dea G",
    username: "dea",
    profileImg: "/avatars/userImage5.jpg",
  },
  {
    _id: "3",
    fullName: "Ranier Tan",
    username: "ranier",
    profileImg: "/avatars/userImage1.jpg",
  },
  {
    _id: "4",
    fullName: "Dea G",
    username: "dea",
    profileImg: "/avatars/userImage5.jpg",
  },
];
